### ISSUE TITLE
Add optional dittybopper installation with argument types for cluster-post-config

### ISSUE THREAD

**Issue by paigerube14** [openshift-qe/ocp-qe-perfscale-ci#184]
Some teams using our workloads might have their own installation of dittybopper installed on there cluster. We need to make dittybopper installation optional
if we do install dittybopper, we need to be able to pass the github url and branch that we want to install from to have more flexibility

**Comment by paigerube14** [comment]
This option will need to be added to cluster-post-config, cluster-worker-scaling, kube-burner, loaded-upgrade (at the very least)

**Comment by nathan-weinberg** [comment]
@paigerube14 please let myself or @memodi know if we can assist with this effort!

**Comment by memodi** [comment]
Thanks @paigerube14 for creating this issue.
I think besides having custom URL/branch, having custom args to be supplied with dittybopper's `./deploy.sh` would also be helpful.

**Comment by paigerube14** [comment]
@memodi that seems like a lot of options for dittybopper to have. Are we able to set environment variables to use to pass parameters to deploy.sh to do the same functionality? What specific parameters do you usually pass? 

Just don't want the options to get too extensive here and then have to add to every other workload.

**Comment by memodi** [comment]
> @memodi that seems like a lot of options for dittybopper to have. Are we able to set environment variables to use to pass parameters to deploy.sh to do the same functionality? What specific parameters do you usually pass?
> 
> Just don't want the options to get too extensive here and then have to add to every other workload.

@paigerube14 - I was envisioning in Jenkins it would like string parameter where user can pass in any options they would like and it would be passed on to dittybopper as opposed to having every option as a  Jenkins parameter. 
We typically use `-t` and `-i` options.

**Comment by nathan-weinberg** [comment]
Perhaps a simple `string` parameter that allows for adding arguments to the `deploy.sh` command. It could be blank as a default as to not change current functionality, and the NO QE team can fill it in either manually or in our calling automation.

**Comment by paigerube14** [comment]
with the closed PR this issue should be fixed
