### ISSUE TITLE
scale up should support machineset number other than 3

### ISSUE THREAD

**Issue by qiliRedHat** [openshift-qe/ocp-qe-perfscale-ci#2]
scale up only support 3 machinesets cluster.
https://github.com/openshift-qe/ocp-qe-perfscale-ci/blob/ff917f00525a04ecf982e3fbef9b8c8f049d17a6/Jenkinsfile#L58
But for some cluster there is only one machineset, for example
Azure installed with private-templates/functionality-testing/aos-4_8/ipi-on-azure/versioned-installer-ovn template has only one machineset, when I scale it to 100 workers in jenkins job, it actually scales to 34.

```
% oc get --no-headers machinesets -A                         
openshift-machine-api   qili-48-zaure-rqzx4-worker-northcentralus   34    34    33    33    4h27m
```

**Comment by paigerube14** [comment]
Think this should be working now @qiliRedHat, have you tried this recently?

**Comment by qiliRedHat** [comment]
@paigerube14 I verified this on Azure install with 1 machineset https://mastern-jenkins-csb-openshift-qe.apps.ocp4.prod.psi.redhat.com/job/scale-ci/job/e2e-benchmarking-multibranch-pipeline/job/cluster-workers-scaling/195/console. It works well now. Thanks for the fix!
