### ISSUE TITLE
Missing info about machinesets and nodes after failed scaling job

### ISSUE THREAD

**Issue by skordas** [openshift-qe/ocp-qe-perfscale-ci#89]
After failed scaling job `cluster-workers-scaling` There is no additional information about not ready machineset or nodes.
Need to add
oc describe machineset
and
oc describe node

**Comment by paigerube14** [comment]
Rough start to this on: https://github.com/paigerube14/ocp-qe-perfscale-ci/tree/cluster-workers-scaling

Around this [line](https://github.com/paigerube14/ocp-qe-perfscale-ci/blob/ffbd10df235594120c0ea30952d9c389efc648ee/Jenkinsfile#L95)

**Comment by paigerube14** [comment]
@skordas what are your thoughts on lowering the number of attempts in this repo as well? Right now it is set to 180 attempts and sleeps for 60 seconds so 3 hours of waiting. That seems like too high to me. What do you think?

**Comment by skordas** [comment]
based on experience.... even 2 is a lot. Maybe 120 would be enough.

**Comment by skordas** [comment]
100 also works. Let's wait and see. If needed, then we can change this once again.

**Comment by paigerube14** [comment]
This is now working, closing because PR has been merge: https://github.com/openshift-qe/ocp-qe-perfscale-ci/issues/89
