### ISSUE TITLE
Network-perf tests rewritten and now failing   

### ISSUE THREAD

**Issue by paigerube14** [openshift-qe/ocp-qe-perfscale-ci#96]
@mffiedler It looks like the network-perf tests were rewritten to all use the [run.sh](https://github.com/cloud-bulldozer/e2e-benchmarking/blob/master/workloads/network-perf/run.sh) script with different env variables setting which test to run. 

See run in jenkins for failure....e2e-benchmarking-multibranch-pipeline/job/network-perf-pod-network-test/154/console

Have you ran/seen this? I am not super familiar with these tests so wanted to check with you on if the below sounds correct 
I'm guessing the following: 
WORKLOAD=pod2pod is for branch [network-perf-pod-network-test](https://github.com/openshift-qe/ocp-qe-perfscale-ci/tree/network-perf-pod-network-test)

WORKLOAD=hostnet is for [network-perf-hostnetwork-network-test](https://github.com/openshift-qe/ocp-qe-perfscale-ci/tree/network-perf-hostnetwork-network-test)

WORKLOAD= pod2svc is for [network-perf-serviceip-network-test](https://github.com/openshift-qe/ocp-qe-perfscale-ci/tree/network-perf-serviceip-network-test)

I see a couple more options in the documentation with setting network policy to true. Should we add that in as a parameter for each of the tests to cover each of the scenarios listed?

**Comment by paigerube14** [comment]
Start of this work seen here: https://github.com/paigerube14/ocp-qe-perfscale-ci/tree/network-perf-pod-network-test

**Comment by paigerube14** [comment]
Another option here would be to combine the 3 network-perf branches into a single branch. 

It would consist of 2 variables: 
1. .a workload type variable which would have a drop down of the 3 options (pod2pod, hostnet, and pod2svc)
2. a boolean network policy variable 

@skordas @rpattath @qiliRedHat are you familiar with this test or have any input on the layout

**Comment by qiliRedHat** [comment]
@paigerube14 I haven't run network scale-ci, but looking at the 3 existing network Jenkins jobs, they don't have special parameter to input besides ENV_VARS. So I like your idea of combine the 3 network-perf branches into a single branch. That will be more clean.

**Comment by paigerube14** [comment]
I had went ahead with this in case we wanted to go that route and test things out. Started it here: https://github.com/paigerube14/ocp-qe-perfscale-ci/tree/network-perf

**Comment by paigerube14** [comment]
Closing with PR merged: https://github.com/openshift-qe/ocp-qe-perfscale-ci/pull/102
